<?php
/**
 * @file
 * Code for the SMASH Events feature.
 */

include_once 'smash_events.features.inc';

/**
 * Force event breadcrumb
 */
function smash_events_view($node, $view_mode) {
  if ($view_mode == 'full' && node_is_page($node) && $node->type == 'event') {
    $breadcrumb = array();
    $breadcrumb[] = l(t('Home'), NULL);
    $breadcrumb[] = l(t('Events'), 'events');
    drupal_set_breadcrumb($breadcrumb);
  }

  return $node;
}
