; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.16"
projects[drupal][patch][] = http://drupal.org/files/core-js-drupal-log-1232416-100-D7.patch

projects[backup_migrate][version] = "2.4"

projects[colorbox][version] = "1.4"

projects[context][version] = "3.0-beta4"

projects[ctools][version] = "1.2"

projects[date][version] = "2.6"

projects[diff][version] = "2.0"

projects[ds][version] = "2.0"

projects[entity][version] = "1.0-rc3"

projects[entityreference][version] = "1.0-rc5"

projects[features][version] = "1.0"

projects[field_collection][version] = "1.0-beta4"

projects[field_group][version] = "1.1"

projects[media][version] = "1.2"

projects[migrate][version] = "2.4"

projects[globalredirect][version] = "1.5"

projects[libraries][version] = "1.0"

projects[link][version] = "1.0"

projects[mailchimp][version] = "2.7"

projects[markdown][version] = "1.0"

projects[menu_views][version] = "1.4"

projects[migrate][version] = "2.4"

projects[migrate_extras][version] = "2.4"

projects[panels][version] = "3.3"

projects[pathauto][version] = "1.2"

projects[redirect][version] = "1.0-rc1"

projects[registration][version] = "1.0-beta3"

projects[special_menu_items][version] = "1.0"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.4"

projects[transliteration][version] = "3.1"

projects[uuid][version] = "1.0-alpha3"

projects[uuid_features][version] = "1.0-alpha1"

projects[views][version] = "3.5"
projects[views][patch][] = "http://drupal.org/files/views_ajax_submit_back_2.patch"

projects[views_bulk_operations][version] = "3.0"

projects[webform][version] = "3.18"

projects[webform_conditional][version] = "1.0-beta1"

projects[webform_multifile][version] = "1.2"

projects[wordpress_migrate][version] = "2.0"

projects[workbench][version] = "1.1"

projects[workbench_access][version] = "1.0"

projects[workbench_moderation][version] = "1.2"

projects[wysiwyg][version] = "2.2"

projects[xmlsitemap][version] = "2.0-rc1"

; Themes
projects[omega][version] = "3.x"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "http://www.jacklmoore.com/colorbox/colorbox.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"


