; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash][download][type] = ""
projects[smash][download][url] = ""
projects[smash][type] = "module"

projects[views_bulk_operations][version] = "3.0-rc1"

projects[backup_migrate][version] = "2.4"

projects[ctools][version] = "1.2"

projects[date][version] = "2.6"

projects[diff][version] = "2.0"

projects[ds][version] = "1.5"

projects[entity][version] = "1.0-rc3"

projects[entityreference][version] = "1.0-rc3+2-dev"

projects[features][version] = "1.0"

projects[field_collection][version] = "1.0-beta4"

projects[field_group][version] = "1.1"

projects[media][version] = "1.2"

projects[globalredirect][version] = "1.5"

projects[libraries][version] = "1.0"

projects[link][version] = "1.0"

projects[mailchimp][version] = "2.6"

projects[markdown][version] = "1.0"

projects[menu_views][version] = "1.3"

projects[migrate][version] = "2.4"

projects[migrate_extras][version] = "2.4"

projects[panels][version] = "3.3"

projects[pathauto][version] = "1.2"

projects[redirect][version] = "1.0-beta4"

projects[registration][version] = "1.0-beta3"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_basic_config][download][type] = ""
projects[smash_basic_config][download][url] = ""
projects[smash_basic_config][type] = "module"
projects[smash_basic_config][version] = "0.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_events][download][type] = ""
projects[smash_events][download][url] = ""
projects[smash_events][type] = "module"
projects[smash_events][version] = "0.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_guests][download][type] = ""
projects[smash_guests][download][url] = ""
projects[smash_guests][type] = "module"
projects[smash_guests][version] = "0.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_locations][download][type] = ""
projects[smash_locations][download][url] = ""
projects[smash_locations][type] = "module"
projects[smash_locations][version] = "0.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_migration][download][type] = ""
projects[smash_migration][download][url] = ""
projects[smash_migration][type] = "module"
projects[smash_migration][version] = "0.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_news][download][type] = ""
projects[smash_news][download][url] = ""
projects[smash_news][type] = "module"
projects[smash_news][version] = "0.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_vendors][download][type] = ""
projects[smash_vendors][download][url] = ""
projects[smash_vendors][type] = "module"
projects[smash_vendors][version] = "0.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_workflow_configuration][download][type] = ""
projects[smash_workflow_configuration][download][url] = ""
projects[smash_workflow_configuration][type] = "module"
projects[smash_workflow_configuration][version] = "0.2"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.2"

projects[transliteration][version] = "3.1"

projects[uuid][version] = "1.0-alpha3"

projects[uuid_features][version] = "1.0-alpha1"

projects[views][version] = "3.5"

projects[webform][version] = "3.18"

projects[webform_conditional][version] = "1.0-beta1"

projects[webform_multifile][version] = "1.2"

projects[wordpress_migrate][version] = "2.0"

projects[workbench][version] = "1.1"

projects[workbench_access][version] = "1.0"

projects[workbench_moderation][version] = "1.2"

projects[wysiwyg][version] = "2.1"

projects[xmlsitemap][version] = "2.0-rc1"

; Themes
projects[omega][version] = "3.x"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"


