<?php
/**
 * @file
 * Code for the SMASH Vendors feature.
 */

include_once 'smash_vendors.features.inc';

/**
 * Force vendor breadcrumb
 */
function smash_vendors_node_view($node, $view_mode) {
  if ($view_mode == 'full' && node_is_page($node) && $node->type == 'vendor') {
    $breadcrumb = array();
    $breadcrumb[] = l(t('Home'), NULL);
    $breadcrumb[] = l(t('Vendors'), 'vendors');
    drupal_set_breadcrumb($breadcrumb);
    
    $trail[] = array(
      'title' => t('Home'),
      'href' => '<front>',
    );
    $trail[] = array(
      'title' => t('Vendors'),
      'href' => 'vendors',
    );
    menu_set_active_trail($trail);
  }
}

function smash_vendors_ds_fields_info_alter(&$fields, $entity_type) {
  if ($entity_type == 'node') {
    $fields['title']['function'] = 'smash_vendors_custom_node_title';
  }
}

function smash_vendors_custom_node_title($field) {
  $output = '';
  $settings = isset($field['formatter_settings']) ? $field['formatter_settings'] : array();
  $settings += $field['properties']['default'];
  // Basic string.
  if (isset($settings['link text'])) {
    $output = t($settings['link text']);
  }
  elseif (isset($field['properties']['entity_render_key']) && isset($field['entity']->{$field['properties']['entity_render_key']})) {
    if ($field['entity_type'] == 'user' && $field['properties']['entity_render_key'] == 'name') {
      $output = format_username($field['entity']);
    }
    else {
      $output = $field['entity']->{$field['properties']['entity_render_key']};
    }
  }

  if (empty($output)) {
    return;
  }

  $output = filter_xss($output, array('em', 'strong'));

  // Link.
  if ($settings['link']) {
    if (isset($field['entity']->uri['path'])) {
      $path = $field['entity']->uri['path'];
    }
    else {
      $uri_info = entity_uri($field['entity_type'], $field['entity']);
      $path = $uri_info['path'];
    }
    $output = l($output, $path, array('html' => TRUE));
  }

  // Special vendor hax
  if ($field['bundle'] == 'vendor' && !empty($field['entity']->field_website_url[LANGUAGE_NONE])) {
    $path = $field['entity']->field_website_url[LANGUAGE_NONE][0]['url'];
    $output = l($output, $path, array('html' => TRUE));
  }

  // Wrapper and class.
  if (!empty($settings['wrapper'])) {
    $wrapper = check_plain($settings['wrapper']);
    $class = (!empty($settings['class'])) ? ' class="' . check_plain($settings['class']) . '"' : '';
    $output = '<' . $wrapper . $class . '>' . $output . '</' . $wrapper . '>';
  }
  return $output;
}

/**
 * Implements hook_field_formatter_info().
 */
function smash_vendors_field_formatter_info() {
  return array(
    'smash_vendors_link' => array(
      'label' => t('Custom vendor link'),
      'field types' => array('link_field'),
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function smash_vendors_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $elements = array();
  foreach ($items as $delta => $item) {
    $elements[$delta] = array(
      '#theme' => 'svlink_formatter_' . $display['type'],
      '#element' => $item,
      '#field' => $instance,
      '#display' => $display,
    );
  }
  return $elements;
}

/**
 * Implements hook_theme().
 */
function smash_vendors_theme() {
  return array(
    'svlink_formatter_smash_vendors_link' => array(
      'variables' => array('element' => NULL),
    ),
  );
}

/**
 * Formats a link.
 */
function theme_svlink_formatter_smash_vendors_link($vars) {
  $link_options = $vars['element'];
  unset($link_options['title']);
  unset($link_options['url']);

  if (isset($link_options['attributes']['class'])) {
    $link_options['attributes']['class'] = array($link_options['attributes']['class']);
  }

  if (strpos($vars['element']['url'], 'twitter.com') !== FALSE) {
    $link_options['attributes']['class'][] = 'svlink-twitter';
  }
  if (strpos($vars['element']['url'], 'facebook.com') !== FALSE) {
    $link_options['attributes']['class'][] = 'svlink-facebook';
  }
  if (strpos($vars['element']['url'], 'tumblr.com') !== FALSE) {
    $link_options['attributes']['class'][] = 'svlink-tumblr';
  }
  if (strpos($vars['element']['url'], 'deviantart.com') !== FALSE) {
    $link_options['attributes']['class'][] = 'svlink-deviantart';
  }
  if (strpos($vars['element']['url'], 'etsy.com') !== FALSE) {
    $link_options['attributes']['class'][] = 'svlink-etsy';
  }

  // Display a normal link if both title and URL are available.
  if (!empty($vars['element']['title']) && !empty($vars['element']['url'])) {
    return l($vars['element']['title'], $vars['element']['url'], $link_options);
  }
  // If only a title, display the title.
  elseif (!empty($vars['element']['title'])) {
    return check_plain($vars['element']['title']);
  }
  elseif (!empty($vars['element']['url'])) {
    return l($vars['element']['title'], $vars['element']['url'], $link_options);
  }
}