<?php
/**
 * @file
 * Code for the SMASH Vendors feature.
 */

include_once 'smash_vendors.features.inc';

/**
 * Force vendor breadcrumb
 */
function smash_vendors_view($node, $view_mode) {
  if ($view_mode == 'full' && node_is_page($node) && $node->type == 'vendor') {
    $breadcrumb = array();
    $breadcrumb[] = l(t('Home'), NULL);
    $breadcrumb[] = l(t('Vendors'), 'vendors');
    drupal_set_breadcrumb($breadcrumb);
  }

  return $node;
}

