<?php
/**
 * @file
 * Code for the SMASH News feature.
 */

include_once 'smash_news.features.inc';

/**
 * Force news breadcrumb
 */
function smash_news_view($node, $view_mode) {
  if ($view_mode == 'full' && node_is_page($node) && $node->type == 'article') {
    $breadcrumb = array();
    $breadcrumb[] = l(t('Home'), NULL);
    $breadcrumb[] = l(t('News'), 'news');
    drupal_set_breadcrumb($breadcrumb);
  }

  return $node;
}

