<?php
/**
 * @file
 * Code for the SMASH Guests feature.
 */

include_once 'smash_guests.features.inc';

/**
 * Force event breadcrumb
 */
function smash_guests_node_view($node, $view_mode) {
  if ($view_mode == 'full' && node_is_page($node) && $node->type == 'guest') {
    $breadcrumb = array();
    $breadcrumb[] = l(t('Home'), NULL);
    $breadcrumb[] = l(t('Guests'), 'guests');
    drupal_set_breadcrumb($breadcrumb);
    
    $trail[] = array(
      'title' => t('Home'),
      'href' => '<front>',
    );
    $trail[] = array(
      'title' => t('Guests'),
      'href' => 'guests',
    );
    menu_set_active_trail($trail);
  }
}

